name: Build and Test ASP.NET Core App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Setup .NET Core
        run: dotnet restore AspNetCoreMVC.sln

      - name: Build solution
        run: dotnet build AspNetCoreMVC.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test AspNetCoreMVC.sln --no-build --configuration Release
